CC=g++
STD=c++11

clock_demo:
	$(CC) -o output clock_demo.cpp -std=$(STD)

ratio_demo:
	$(CC) -o output ratio_demo.cpp -std=$(STD)

duration_demo:
	$(CC) -o output duration_demo.cpp -std=$(STD)

clean:
	rm output
