CC=g++
CCSTD=c++11

promise:
	$(CC) -o output promise.cpp -std=$(CCSTD) -lpthread

thread_demo:
	$(CC) -o output thread_demo.cpp -std=$(CCSTD) -lpthread

async_demo:
	$(CC) -o output async_demo.cpp -std=$(CCSTD) -lpthread

clean:
	rm output
